version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - node
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "4000:4000"
