# name: Build and deploy Node.js app to Azure Web App - Bobounsic

# on:
#   push:
#     branches: [ "main" ]
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Node.js (for Azure compatibility)
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20.x'

#       - name: Install Bun
#         run: |
#           curl -fsSL https://bun.sh/install | bash
#           echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
#           echo "$HOME/.bun/bin" >> $GITHUB_PATH

#       - name: Install dependencies and build
#         working-directory: ./bounsic-front
#         run: |
#           bun install
#           bun run build

#       - name: Create production server file
#         working-directory: ./bounsic-front
#         run: |
#           cat > server.js << 'EOL'
#           const express = require('express');
#           const path = require('path');
#           const app = express();
#           app.use(express.static(path.join(__dirname, 'dist')));
#           const port = process.env.PORT || 3000;
#           app.listen(port, () => console.log(`Server running on port ${port}`));
#           EOL
          
#           bun add express

#       - name: Zip artifact for deployment
#         working-directory: ./bounsic-front
#         run: |
#           mkdir -p ../deployment
#           zip -r ../deployment/release.zip ./* -x 'node_modules/*'

#       - name: Upload artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: node-app
#           path: ./deployment/release.zip

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
#     # ESTOS PERMISOS SON CRUCIALES
#     permissions:
#       contents: read
#       id-token: write  # ← Esto soluciona el error de login

#     steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: node-app
          
#       - name: Unzip artifact for deployment
#         run: unzip release.zip
        
#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_30DC8FFE44C04E7BB4C8CCD837E3F1DC }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D729DA70D0384338811F9E5103F4F64D }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D75B860C19064FC593DF7E1E569F2288 }}

#       - name: Deploy to Azure Web App
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'Bobounsic'
#           slot-name: 'Production'
#           package: ./release.zip
#           runtime: 'NODE|20-lts'
