name: Build and Deploy to Azure Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 🔹 Instalar Bun y agregarlo al PATH
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV
          source $HOME/.bashrc
        shell: bash

      # 🔹 Verificar que los archivos existen antes del build
      - name: Verify required files
        run: |
          ls -l ./bounsic-front/package.json || echo "ERROR: package.json no encontrado"
          ls -l ./bounsic-front/bun.lock || echo "ERROR: bun.lock no encontrado"
          ls -R ./bounsic-front/dist || echo "ERROR: La carpeta dist no existe"

      # 🔹 Instalar dependencias y construir el frontend
      - name: Install dependencies and build frontend
        working-directory: ./bounsic-front
        run: |
          bun install
          bun run build

      # 🔹 Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 🔹 Iniciar sesión en Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: bounsiccontainerregistery.azurecr.io
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD }}

      # 🔹 Construir y subir imagen del backend
      - name: Build and push backend (Node.js) image
        uses: docker/build-push-action@v3
        with:
          context: .  # 🔹 Usa la raíz del repo para evitar problemas de rutas
          file: ./bounsic-front/Dockerfile.node
          push: true
          tags: bounsiccontainerregistery.azurecr.io/bounsic-front-node:${{ github.sha }}

      # 🔹 Construir y subir imagen del frontend
      - name: Build and push frontend (Nginx) image
        uses: docker/build-push-action@v3
        with:
          context: .  # 🔹 Usa la raíz del repo para evitar problemas de rutas
          file: ./bounsic-front/Dockerfile.nginx
          push: true
          tags: bounsiccontainerregistery.azurecr.io/bounsic-front-nginx:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      # 🔹 Desplegar backend en Azure
      - name: Deploy Backend (Node.js) to Azure Web App
        id: deploy-backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bounsic-front-node'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE_NODE }}
          images: 'bounsiccontainerregistery.azurecr.io/bounsic-front-node:${{ github.sha }}'

      # 🔹 Desplegar frontend en Azure
      - name: Deploy Frontend (Nginx) to Azure Web App
        id: deploy-frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bounsic-front-nginx'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          images: 'bounsiccontainerregistery.azurecr.io/bounsic-front-nginx:${{ github.sha }}'
