name: Build and Deploy to Azure Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install dependencies and build frontend
        working-directory: ./bounsic-front
        run: |
          bun install
          bun run build

      - name: Verify build output
        run: ls -R ./bounsic-front/dist

      - name: Verify bun.lock file
        run: ls -l ./bounsic-front/bun.lock || echo "bun.lock no encontrado"
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: bounsiccontainerregistery.azurecr.io
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_712540B034984E568F19540CBDB646F1 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_48B0A9888467461F9980B8A659B9DEC2 }}

      - name: Build and push backend (Node.js) image
        uses: docker/build-push-action@v3
        with:
          context: ./bounsic-front  # 🔹 Asegura que usa la carpeta correcta
          file: ./bounsic-front/Dockerfile.node
          push: true
          tags: bounsiccontainerregistery.azurecr.io/bounsic-front-node:${{ github.sha }}

      - name: Build and push frontend (Nginx) image
        uses: docker/build-push-action@v3
        with:
          context: ./bounsic-front  # 🔹 Asegura que usa la carpeta correcta
          file: ./bounsic-front/Dockerfile.nginx
          push: true
          tags: bounsiccontainerregistery.azurecr.io/bounsic-front-nginx:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy Backend (Node.js) to Azure Web App
        id: deploy-backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bounsic-front-node'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE_NODE }}
          images: 'bounsiccontainerregistery.azurecr.io/bounsic-front-node:${{ github.sha }}'

      - name: Deploy Frontend (Nginx) to Azure Web App
        id: deploy-frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bounsic-front-nginx'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_40660E4ACB984F97B4E7395743AE5A79 }}
          images: 'bounsiccontainerregistery.azurecr.io/bounsic-front-nginx:${{ github.sha }}'
